[tool.isort]
line_length = 100
ignore_whitespace = true
profile = "black"

[tool.black]
line-length = 100
target-version = ['py39']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[tool.mypy]
python_version = "3.9"
check_untyped_defs = true
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "proj.settings"

[tool.pylint.MASTER]
load-plugins = "pylint_django"
django-settings-module = "proj.settings"

[tool.pylint.FORMAT]
max-line-length = 100

[tool.bandit]
exclude_dirs = ["tests", "venv", ".venv"]
