# Generated by Django 5.1.2 on 2024-10-29 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ThirdPartyTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("product_rid", models.CharField(max_length=100)),
                ("test_date", models.DateField()),
                ("purity_percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "pdf_file",
                    models.FileField(
                        storage="proj.storage_backends.PublicMediaStorage",
                        upload_to="third_party_tests/",
                    ),
                ),
            ],
            options={
                "ordering": ["-test_date"],
            },
        ),
    ]
