# Generated by Django 5.1.2 on 2024-10-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thirdpartytest",
            name="pdf_file",
            field=models.FileField(upload_to="third_party_tests/"),
        ),
    ]
